quarkus:
  http:
    port: 8080
  datasource:
    db-kind: mysql
    username: blessrom_user
    password: "XIcsH5R#/WFhZQTz"
    jdbc:
      url: jdbc:mysql://127.0.0.1:3306/blessrom_db
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
    packages: com.blessrom.travel.entidades
  redis:
    hosts: redis://localhost:6379
  langchain4j:
    redis:
      dimension: 1536
      index-name: "idx:memoria"
      metadata-fields: "customer_id" # Esto le dice a Redis que cree un TAG para filtrar
  whatsapp:
    verify-token: blessrom_token_2026

blessrom:
  bot:
    openai-key: ${OPENAI_API_KEY}
  sincronizador-api:
    url: "http://localhost:8082"

botbless:
  web-api-url: "http://localhost:8083"
  internal-secret: "botbless-secret-2026"
