quarkus:
  http:
    port: 8080
  datasource:
    db-kind: mysql
    username: blessrom_user
    password: "XIcsH5R#/WFhZQTz"
    jdbc:
      url: jdbc:mysql://127.0.0.1:3306/blessrom_db
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
    packages: com.blessrom.travel.entidades
  redis:
    hosts: redis://localhost:6379
  whatsapp:
    verify-token: blessrom_token_2026

blessrom:
  bot:
    openai-key: ${OPENAI_API_KEY}
  sincronizador-api:
    url: "http://localhost:8082"
